import type { DigitalThreadSnapshot } from "./types";

export const demoDigitalThreadData: DigitalThreadSnapshot = {
  asOf: "2026-08-27T14:02:16Z",
  lastReconciledSecondsAgo: 8,
  monitoringWindowDays: 30,
  metrics: [
    {
      label: "CONNECTOR HEALTH",
      value: "7 / 8",
      detail: "One connector above latency SLO",
      tone: "amber",
    },
    {
      label: "DELIVERY SUCCESS",
      value: "99.94%",
      detail: "Rolling 30-day business events",
      tone: "green",
    },
    {
      label: "P95 PROPAGATION",
      value: "2.1s",
      detail: "Source to final projection",
      tone: "cyan",
    },
    {
      label: "CONTEXT JOIN",
      value: "99.72%",
      detail: "Enterprise identity resolved",
      tone: "cyan",
    },
    {
      label: "OPEN MISMATCHES",
      value: "3",
      detail: "Oldest unresolved · 1m 42s",
      tone: "amber",
    },
  ],
  systems: [
    {
      id: "plm",
      label: "PLM",
      sublabel: "Engineering",
      authority: "Part · BOM · revision",
      health: "healthy",
      freshness: "3s",
      position: "node-nw",
      icon: "git-branch",
    },
    {
      id: "mes",
      label: "MES",
      sublabel: "Execution",
      authority: "WO · operation · genealogy",
      health: "healthy",
      freshness: "1s",
      position: "node-ne",
      icon: "factory",
    },
    {
      id: "erp",
      label: "ERP",
      sublabel: "Inventory / logistics",
      authority: "Lot · inventory · PO",
      health: "warning",
      freshness: "48s",
      position: "node-w",
      icon: "package",
    },
    {
      id: "qms",
      label: "QMS",
      sublabel: "Quality",
      authority: "NCR · CAPA · disposition",
      health: "healthy",
      freshness: "8s",
      position: "node-e",
      icon: "shield-check",
    },
    {
      id: "opc",
      label: "OPC UA",
      sublabel: "Shop floor",
      authority: "Machine · sensor · process",
      health: "healthy",
      freshness: "240ms",
      position: "node-sw",
      icon: "radio",
    },
    {
      id: "knowledge",
      label: "Knowledge",
      sublabel: "Knowledge",
      authority: "Decision · context · guidance",
      health: "healthy",
      freshness: "21s",
      position: "node-se",
      icon: "file-text",
    },
  ],
  events: [
    {
      id: "EVT-9F3A7C",
      domain: "Quality",
      title: "Quality disposition approved",
      object: "NCR-2026-0147 · IN718-26-0814-A",
      source: "QMS",
      sourceSystem: "Quality Management System",
      time: "14:02:11",
      status: "propagated",
      targets: 6,
      latency: "2.3s",
      contract: "quality.disposition.v2",
      correlationId: "WF-MRB-7D91",
      authority:
        "QMS owns disposition; consuming systems receive controlled state projections.",
      description:
        "MRB approved rework for a nonconforming Inconel material lot. The event held affected inventory, quarantined logistics movement, inserted a gated MES operation, refreshed the quality mart, and linked the controlled record into the knowledge index.",
      steps: [
        { id: "quality-source", system: "QMS", action: "Disposition signed and revision 4 made effective", time: "14:02:11.041", latency: "source", state: "approved" },
        { id: "quality-published", system: "Event Bus", action: "quality.disposition.v2 validated and published", time: "14:02:11.218", latency: "177ms", state: "complete" },
        { id: "quality-erp-hold", system: "ERP", action: "Material lot status changed to QA HOLD", time: "14:02:12.064", latency: "846ms", state: "complete" },
        { id: "quality-mes-rework", system: "MES", action: "Rework operation inserted before release gate", time: "14:02:12.487", latency: "1.27s", state: "complete" },
        { id: "quality-wms-quarantine", system: "WMS", action: "Shipment eligibility blocked; quarantine confirmed", time: "14:02:12.728", latency: "1.51s", state: "complete" },
        { id: "quality-analytics", system: "Analytics", action: "Quality and genealogy projections reconciled", time: "14:02:12.903", latency: "1.69s", state: "observed" },
        { id: "quality-knowledge", system: "Knowledge", action: "Knowledge pointer linked to approved QMS record", time: "14:02:13.322", latency: "2.10s", state: "observed" },
      ],
    },
    {
      id: "EVT-B241D8",
      domain: "Engineering",
      title: "Part revision released",
      object: "RS-R1-BKT-042 · Rev C · S/N 185+",
      source: "PLM",
      sourceSystem: "Product Lifecycle Management",
      time: "13:47:26",
      status: "attention",
      targets: 4,
      latency: "—",
      contract: "engineering.revision.v3",
      correlationId: "ECO-02618",
      authority:
        "PLM owns released design and effectivity. Production rollout remains approval-gated.",
      description:
        "Revision C was released with effectivity beginning at serial 185. Three downstream projections updated; MES detected one open work order still pinned to revision B and raised an exception instead of rewriting it.",
      steps: [
        { id: "engineering-source", system: "PLM", action: "ECO-02618 approved; revision C released", time: "13:47:26.002", latency: "source", state: "approved" },
        { id: "engineering-published", system: "Event Bus", action: "engineering.revision.v3 published", time: "13:47:26.141", latency: "139ms", state: "complete" },
        { id: "engineering-erp", system: "ERP", action: "Open purchase lines checked for effectivity", time: "13:47:26.924", latency: "783ms", state: "complete" },
        { id: "engineering-qms", system: "QMS", action: "Training and work-instruction impact review opened", time: "13:47:27.611", latency: "1.47s", state: "observed" },
        { id: "engineering-mes-conflict", system: "MES", action: "WO-88142 Rev B conflict sent to exception queue", time: "13:47:28.079", latency: "1.94s", state: "observed" },
      ],
    },
    {
      id: "EVT-613EE2",
      domain: "Logistics",
      title: "Material lot received",
      object: "PO-451188 · MAT-CUCRZR-0227",
      source: "ERP",
      sourceSystem: "Enterprise Resource Planning",
      time: "13:31:08",
      status: "propagated",
      targets: 4,
      latency: "1.7s",
      contract: "logistics.receipt.v1",
      correlationId: "RCV-11834",
      authority: "ERP owns inventory receipt; QMS owns acceptance status.",
      description:
        "A CuCrZr powder lot was received into quarantine. The lot identity was registered, receiving inspection was opened, and genealogy availability was published without marking the material usable.",
      steps: [
        { id: "logistics-source", system: "ERP", action: "Receipt posted into QUARANTINE location", time: "13:31:08.433", latency: "source", state: "complete" },
        { id: "logistics-published", system: "Event Bus", action: "logistics.receipt.v1 published", time: "13:31:08.602", latency: "169ms", state: "complete" },
        { id: "logistics-identity", system: "Identity Registry", action: "Enterprise material-lot ID assigned", time: "13:31:09.019", latency: "586ms", state: "complete" },
        { id: "logistics-qms", system: "QMS", action: "Receiving inspection RI-01892 created", time: "13:31:09.678", latency: "1.25s", state: "observed" },
        { id: "logistics-analytics", system: "Analytics", action: "Lot genealogy projection appended", time: "13:31:10.102", latency: "1.67s", state: "observed" },
      ],
    },
    {
      id: "EVT-AC09F1",
      domain: "Manufacturing",
      title: "Build anomaly observed",
      object: "BLD-LPBF-0826-017 · Layer 4,812",
      source: "OPC UA",
      sourceSystem: "Shop-floor Edge Gateway",
      time: "13:18:54",
      status: "processing",
      targets: 3,
      latency: "842ms",
      contract: "manufacturing.observation.v4",
      correlationId: "OBS-44C820",
      authority:
        "Machine observations are immutable; MES and QMS determine operational response.",
      description:
        "Melt-pool intensity exceeded the registered control band for seven consecutive samples. Raw telemetry was preserved, MES paused the next transition, and a quality inspection recommendation awaits acknowledgment.",
      steps: [
        { id: "manufacturing-source", system: "OPC UA", action: "Registered sensor observation at layer 4,812", time: "13:18:54.006", latency: "source", state: "complete" },
        { id: "manufacturing-published", system: "Event Bus", action: "manufacturing.observation.v4 published", time: "13:18:54.087", latency: "81ms", state: "complete" },
        { id: "manufacturing-analytics", system: "Analytics", action: "Telemetry and feature vector appended", time: "13:18:54.398", latency: "392ms", state: "observed" },
        { id: "manufacturing-mes-hold", system: "MES", action: "Build transition held pending evaluation", time: "13:18:54.848", latency: "842ms", state: "complete" },
        { id: "manufacturing-qms-pending", system: "QMS", action: "Inspection recommendation awaiting acknowledgment", time: "pending", latency: "open", state: "pending" },
      ],
    },
  ],
  connectors: [
    { id: "plm", system: "PLM / Engineering", owner: "Engineering Systems", method: "Webhook + API", contract: "engineering.* v3", freshness: "3s", backlog: "0", reconcile: "100.00%", health: "healthy" },
    { id: "mes", system: "MES / Execution", owner: "Manufacturing Systems", method: "Event + command API", contract: "manufacturing.* v4", freshness: "1s", backlog: "0", reconcile: "99.99%", health: "healthy" },
    { id: "erp", system: "ERP / Inventory", owner: "Business Systems", method: "CDC + command API", contract: "logistics.* v1", freshness: "48s", backlog: "12", reconcile: "99.84%", health: "warning" },
    { id: "qms", system: "QMS / Quality", owner: "Quality Systems", method: "Webhook + API", contract: "quality.* v2", freshness: "8s", backlog: "0", reconcile: "100.00%", health: "healthy" },
    { id: "wms", system: "WMS / Logistics", owner: "Logistics Systems", method: "EPCIS-like events", contract: "movement.* v1", freshness: "12s", backlog: "0", reconcile: "99.98%", health: "healthy" },
    { id: "opc-ua", system: "OPC UA / Edge", owner: "Manufacturing Data", method: "Gateway → event bus", contract: "observation.* v4", freshness: "240ms", backlog: "0", reconcile: "99.98%", health: "healthy" },
    { id: "knowledge", system: "Knowledge Base", owner: "Knowledge Platform", method: "Webhook + REST", contract: "knowledge.* v2", freshness: "21s", backlog: "3", reconcile: "99.96%", health: "healthy" },
    { id: "analytics", system: "Analytics Warehouse", owner: "Data Platform", method: "Stream + transform", contract: "canonical.* v5", freshness: "6s", backlog: "0", reconcile: "99.99%", health: "healthy" },
  ],
  issues: [
    {
      id: "revision-effectivity",
      severity: "warning",
      title: "Revision effectivity mismatch",
      object: "WO-88142 · RS-R1-BKT-042",
      detail:
        "MES work order remains pinned to Rev B; PLM effective revision is C for serial 185+.",
      age: "15m",
      owner: "Manufacturing Engineering",
    },
    {
      id: "erp-cdc-lag",
      severity: "warning",
      title: "ERP CDC lag above SLO",
      object: "demo-erp → canonical_inventory",
      detail:
        "Current freshness is 48 seconds against a 30-second operating target.",
      age: "7m",
      owner: "Business Systems",
    },
    {
      id: "knowledge-link",
      severity: "info",
      title: "Knowledge link pending",
      object: "CAPA-00182",
      detail:
        "Controlled QMS record is current; its knowledge-base explainer has not linked the new revision.",
      age: "3m",
      owner: "Quality Knowledge",
    },
  ],
  throughput: {
    eventsPerMinute: 286,
    bars: [42, 38, 47, 44, 56, 52, 61, 58, 69, 74, 63, 78, 84, 71, 76, 89, 82, 92, 86, 96, 91, 88, 94, 99],
    stats: [
      { label: "Accepted", value: "17,106" },
      { label: "Deduplicated", value: "23" },
      { label: "DLQ", value: "2", tone: "warning" },
    ],
  },
  governance: {
    score: 87,
    coverage: [
      { label: "Enterprise identity", value: 94, detail: "Parts, lots, work orders, serials" },
      { label: "Contract coverage", value: 88, detail: "Versioned producer / consumer agreements" },
      { label: "Lineage coverage", value: 91, detail: "Source through certified data product" },
      { label: "Knowledge grounding", value: 76, detail: "ACL-aware, versioned source citations" },
    ],
  },
};
